name: Build & Deploy to Cloud Run

on:
  push:
    branches: [ "main" ] # or your desired branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 1.5) Google Cloud Auth
      - name: Google Cloud Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }} 
          project_id: serverless-dev-394718
          
      # 2) Configure Google Cloud auth
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      # 3) Build a Docker image
      - name: Build Docker image
        run: |
          export IMAGE_URI="us-central1-docker.pkg.dev/serverless-dev-394718/gcf-artifacts/test:${{ github.sha }}"
          docker build -t "$IMAGE_URI" .
      
      # 4) Push Docker image to Artifact Registry
      - name: Push to Artifact Registry
        run: |
          export IMAGE_URI="us-central1-docker.pkg.dev/serverless-dev-394718/gcf-artifacts/test:${{ github.sha }}"
          docker push "$IMAGE_URI"

      # 5) Deploy to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          export IMAGE_URI="us-central1-docker.pkg.dev/serverless-dev-394718/gcf-artifacts/test:${{ github.sha }}"
          gcloud run deploy test \
            --image "$IMAGE_URI" \
            --region ${{ secrets.GCP_REGION }} \
            --platform managed \
            --allow-unauthenticated
